# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  unit_tests:
    docker:
      - image: golang:alpine3.16
    steps:
      - checkout
      - run:
          command: CGO_ENABLED=0 cd /root/project/src && go test ./...
          name: Run tests

workflows:
  commit_stage:
    jobs:
      - unit_tests
      - aws-ecr/build-and-push-image:
          requires:
            - unit_tests
#          context: dev_eu-west-1
#          create-repo: true
          region: eu-west-1
          registry-id: AWS_ACCOUNT_ID
          repo: pgf

dev_nightly:
  triggers:
    - schedule:
      cron: "*/5 * * * *"
      filters:
        branches:
          only:
            - main
  jobs:
    - hello:
        name: Hello
        run:
          command: echo "Hello World"
