# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  unit_tests:
    docker:
      - image: golang:alpine3.16
    steps:
      - checkout
      - run:
          command: export CGO_ENABLED=0 && cd /root/project/src && go test ./...
          name: Run tests
  update_app_image:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints:
              - "04:44:53:ac:82:ee:af:a6:b4:72:26:d9:5e:7d:35:f0"
      - run:
          command: |
#            sudo snap install kustomize
#            git clone git@github.com:Adam-Reeves/gitops.playground.config.git
#            git config --global user.name "CircleCI"
#            git config --global user.email adam.j.reeves@outlook.com
#            ssh-add -D
#            ssh-add ~/.ssh/id_rsa_044453ac82eeafa6b47226d95e7d35f0
#            cd gitops.playground.config/k8s/base
#            kustomize edit set image 673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf=673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf:$CIRCLE_SHA1
#            git commit -am "update app image"
#            git push

          name: Update app image
  acceptance_tests:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "04:44:53:ac:82:ee:af:a6:b4:72:26:d9:5e:7d:35:f0"
      - run:
          command: |
            MOST_RECENT_CANDIDATE_SHA1=$(aws ecr describe-images --repository-name pgf --image-ids imageTag=candidate --output json | jq --raw-output '.imageDetails[].imageTags[]' | grep --extended-regexp '\b[0-9a-f]{5,40}\b')
          
            sudo snap install kustomize
            git clone git@github.com:Adam-Reeves/gitops.playground.config.git
            git config --global user.name "CircleCI"
            git config --global user.email adam.j.reeves@outlook.com
            ssh-add -D
            ssh-add ~/.ssh/id_rsa_044453ac82eeafa6b47226d95e7d35f0
            cd gitops.playground.config/k8s/base
            cat kustomization.yaml | grep newTag:$MOST_RECENT_CANDIDATE_SHA1
            
            MANIFEST=$(aws ecr batch-get-image --repository-name pgf --image-ids imageTag=candidate --output json | jq --raw-output --join-output '.images[0].imageManifest')
            aws ecr put-image --repository-name pgf --image-tag production --image-manifest "$MANIFEST"
#            kustomize edit set image 673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf=673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf:EXISTING_TAG
#            git commit -am "update app image"
#            git push
workflows:
  commit_stage:
    jobs:
      - unit_tests
      - aws-ecr/build-and-push-image:
          requires:
            - unit_tests
          region: eu-west-1
          registry-id: AWS_ACCOUNT_ID
          repo: pgf
          tag: $CIRCLE_SHA1,candidate

  acceptance_tests:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - acceptance_tests
